### ISSUE TITLE
Use LangChain tools / support agents

### ISSUE THREAD

**Issue by dexterfichuk** [eyurtsev/kor#129]
Wondering if there's anyway that this could be adapted to use agents, and from that add support for giving the agent tools defined in https://python.langchain.com/en/latest/modules/agents/tools.html to help with extractions?

**Comment by eyurtsev** [comment]
Yeah I think this could be made into a tool invoked by an agent. If not confidential, would you mind sharing your use case or something that shows a similar workflow / usage if confidential?

**Comment by dexterfichuk** [comment]
I can make a simple toy use case for example, but i'd focus on the use of an external tool vs other ways of adding validation to the schema/model.

Say we were making a resume parser. In it we give the text of an applicants resume. Expected output is a list of the validated companies that the applicant has worked for, along with a ton of other data (think first name, last name, portfolio url) that we'd like to schematize and that's why we're using `kor`.

To make sure the applicant didn't make up the company, we would like to use the [Bing Search Tool ](https://python.langchain.com/en/latest/modules/agents/tools/examples/bing_search.html)from langchain to then let the model decide if the company seems valid from the first few results, and if it seems invalid, use that as an opportunity for the model to try getting the company again (maybe it missed part of the title) and try to validate.

So either per field, we'd like to tell it the tools that could be useful for that field, or we could as a whole just give it tools and rely on the tools description to be enough.

Hope this example is clear enough, happy to make more and thanks for responding!

**Comment by eyurtsev** [comment]
Hi Dexter! Thanks for the explanation and sorry for delay responding I was on vacation last week.

Re-summarizing in my own words: What you're proposing is an `extraction agent` that can use external data to validate the information that it is extracting. (e.g., check on crunchbase that a company exists and potentially standardize the company name).

This is a neat idea!

Do you have any thoughts/concerns about extraction times or costs adding up since the agent may re-interact with the content multiple times?

-----

For myself:  This is (likely) distinct from a use-case where there's a specialized agent that can browse through external data sources (e.g., the web) to extracts structured information (e.g., also from the web) from that matches some specified goal.
